name: Trigger auto deployment for energy-forecasting-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/energy-forecasting-app-AutoDeployTrigger-e4c56235-4e16-4a3d-8198-6efb4e1070ed.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ENERGYFORECASTINGAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ENERGYFORECASTINGAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ENERGYFORECASTINGAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: energyregiistry.azurecr.io
          registryUsername: ${{ secrets.ENERGYFORECASTINGAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ENERGYFORECASTINGAPP_REGISTRY_PASSWORD }}
          containerAppName: energy-forecasting-app
          resourceGroup: energy-forecasting-azure_group
          imageToBuild: energyregiistry.azurecr.io/energy-forecasting-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


